version: '3'

services:
  server:
    container_name: trust4ai-bias-evaluator-llm
    image: trust4ai-bias-evaluator-llm:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8001}:${PORT:-8001}
    env_file:
      - .env
    networks:
      - trust4ai-bias-evaluator-llm-network

networks:
  trust4ai-bias-evaluator-llm-network:
    driver: bridge