version: '3'

services:
  server:
    container_name: guard-me
    image: guard-me:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8001}:${PORT:-8001}
    env_file:
      - .env
    networks:
      - guard-me-network
      - global-network

networks:
  guard-me-network:
    driver: bridge
  global-network:
    external: true