version: '3'

services:
  server:
    restart: always
    container_name: trust4ai-bias-evaluator-llm
    image: trust4ai-bias-evaluator-llm:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env