version: '3'

services:
  server:
    container_name: trust4ai-bias-evaluator-llm
    image: trust4ai-bias-evaluator-llm:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env
    networks:
      - trust4ai-bias-evaluator-llm-network
  gemma:
    container_name: gemma
    image: gemma:latest
    build: 
      context: ./Ollama
      dockerfile: Dockerfile
      args:
        MODEL_NAME: "gemma:2b"
    ports:
      - "11434:11434"
    volumes:
      - gemma_data:/root/.ollama
    networks:
      - trust4ai-bias-evaluator-llm-network
  dolphin-phi:
    container_name: dolphin-phi
    image: dolphin-phi:latest
    build: 
      context: ./Ollama
      dockerfile: Dockerfile
      args:
        MODEL_NAME: "dolphin-phi"
    ports:
      - "11435:11434"
    volumes:
      - dolphin-phi_data:/root/.ollama
    networks:
      - trust4ai-bias-evaluator-llm-network

volumes:
  gemma_data:
  dolphin-phi_data:

networks:
  trust4ai-bias-evaluator-llm-network:
    driver: bridge